import os
from typing import List
from tenacity import retry, stop_after_attempt, wait_random_exponential

from models.Base import BaseModel
from vllm import LLM, SamplingParams

from openai import OpenAI


class VLLMModel():
    def __init__(
        self,
        model_id="/shared/models/hf/Meta-Llama-3-8B-Instruct",
        tensor_parallel_size=2,
        dtype="bfloat16",
    ):
        self.model_id = model_id
        # self.llm = LLM(
        #     model=model_id,
        #     tensor_parallel_size=tensor_parallel_size,
        #     dtype=dtype,
        # )
        self.client = OpenAI(
            base_url="http://localhost:8000/v1",
            api_key="token-abc123",
            timeout=300
            )


    # def _messages_to_prompt(self, messages: List[dict]) -> str:
    #     """
    #     Convert list of OpenAI-style messages into a proper chat prompt.
    #     vLLM does not natively support messages; user must build prompt manually.
    #     """
    #     chat = ""
    #     for msg in messages:
    #         role = msg["role"]
    #         content = msg["content"]
    #         if role == "system":
    #             chat += f"<|system|>\n{content}\n"
    #         elif role == "user":
    #             chat += f"<|user|>\n{content}\n"
    #         elif role == "assistant":
    #             chat += f"<|assistant|>\n{content}\n"
    #         else:
    #             chat += f"<|{role}|>\n{content}\n"
    #     chat += "<|assistant|>\n"  # assistant is expected to generate next
    #     return chat


    # @retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(5))
    # def generate(
    #     self,
    #     messages: List,
    #     temperature=0,
    #     presence_penalty=0,
    #     frequency_penalty=0,
    #     max_tokens=5000
    # ) -> str:

    #     prompt = self._messages_to_prompt(messages)

    #     sampling_params = SamplingParams(
    #         temperature=temperature,
    #         max_tokens=max_tokens,
    #         presence_penalty=presence_penalty,
    #         frequency_penalty=frequency_penalty,
    #     )

    #     outputs = self.llm.generate(
    #         [prompt],                  # batch size = 1
    #         sampling_params=sampling_params
    #     )

    #     if not outputs or not outputs[0].outputs:
    #         raise ValueError("No response generated by vLLM.")

    #     return outputs[0].outputs[0].text.strip()

    @retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(5))
    def generate(self, 
                 messages: List, 
                 temperature=1, 
                 presence_penalty=0, 
                 frequency_penalty=0.4, 
                 max_tokens=5000) -> str:
        try:
            response = self.client.chat.completions.create(
                model=self.model_id,
                prompt="Hello, how are you?",
                temperature=temperature,
            )
            if not response or not hasattr(response, 'choices') or len(response.choices) == 0:
                raise ValueError("No response choices returned from the API.")
            output = response.choices[0].message.content
        except Exception as e:
            print(f"Error in generate resposne {e}")
            output = None
        
        return output