import os
from typing import List
from tenacity import retry, stop_after_attempt, wait_random_exponential

from models.Base import BaseModel
from vllm import LLM, SamplingParams

from openai import OpenAI


class VLLMModel():
    def __init__(
        self,
        model_id="/shared/models/hf/Qwen3.5-35B-A3B",
        tensor_parallel_size=2,
        dtype="bfloat16",
        base_url="http://localhost:8001/v1",
        api_key="token-abc123",
    ):
        self.model_id = model_id
        # self.llm = LLM(
        #     model=model_id,
        #     tensor_parallel_size=tensor_parallel_size,
        #     dtype=dtype,
        # )
        self.client = OpenAI(
            base_url=base_url,
            api_key=api_key,
            timeout=300
            )
        self.system_prompt = (
            "You are an expert programmer. Before generating the final code, "
            "strictly plan your logic step-by-step in the thinking phase. "
            "Ensure your thoughts remain coherent, focused on the technical "
            "implementation, and written in clear natural language. Never "
            "output repeating numbers or symbols."
        )


    # def _messages_to_prompt(self, messages: List[dict]) -> str:
    #     """
    #     Convert list of OpenAI-style messages into a proper chat prompt.
    #     vLLM does not natively support messages; user must build prompt manually.
    #     """
    #     chat = ""
    #     for msg in messages:
    #         role = msg["role"]
    #         content = msg["content"]
    #         if role == "system":
    #             chat += f"<|system|>\n{content}\n"
    #         elif role == "user":
    #             chat += f"<|user|>\n{content}\n"
    #         elif role == "assistant":
    #             chat += f"<|assistant|>\n{content}\n"
    #         else:
    #             chat += f"<|{role}|>\n{content}\n"
    #     chat += "<|assistant|>\n"  # assistant is expected to generate next
    #     return chat


    # @retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(5))
    # def generate(
    #     self,
    #     messages: List,
    #     temperature=0,
    #     presence_penalty=0,
    #     frequency_penalty=0,
    #     max_tokens=5000
    # ) -> str:

    #     prompt = self._messages_to_prompt(messages)

    #     sampling_params = SamplingParams(
    #         temperature=temperature,
    #         max_tokens=max_tokens,
    #         presence_penalty=presence_penalty,
    #         frequency_penalty=frequency_penalty,
    #     )

    #     outputs = self.llm.generate(
    #         [prompt],                  # batch size = 1
    #         sampling_params=sampling_params
    #     )

    #     if not outputs or not outputs[0].outputs:
    #         raise ValueError("No response generated by vLLM.")

    #     return outputs[0].outputs[0].text.strip()

    @retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(5))
    def generate(self, 
                 messages: List, 
                 temperature=1, 
                 presence_penalty=0, 
                 frequency_penalty=0,
                 max_tokens=4096,
                 top_p=0.95,
                 min_p=0.05,
                 top_k=20,
                 repetition_penalty=1.0,
                 enable_thinking=True) -> str:
        if not messages or messages[0].get("role") != "system":
            messages = [
                {"role": "system", "content": self.system_prompt},
                *messages,
            ]
        response = self.client.chat.completions.create(
            model=self.model_id,
            messages=messages,
            max_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p,
            presence_penalty=presence_penalty,
            frequency_penalty=frequency_penalty,
            extra_body={
                "repetition_penalty": repetition_penalty,
                "min_p": min_p,
                "top_k": top_k,
                "chat_template_kwargs": {
                    "enable_thinking": enable_thinking,
                },
            },
        )
        if not response or not hasattr(response, 'choices') or len(response.choices) == 0:
            raise ValueError("No response choices returned from the API.")
        choice = response.choices[0]
        message = choice.message
        output = message.content
        if output is not None:
            output = output.strip()
        if not output:
            reasoning = (
                getattr(message, "reasoning", None)
                or getattr(message, "reasoning_content", None)
            )
            raise ValueError(
                "VLLM returned reasoning but no final content "
                f"(finish_reason={choice.finish_reason}, "
                f"reasoning_chars={len(reasoning or '')}). "
                "Increase max_tokens or disable thinking."
            )
        return output
